package com.example.upright

data class S(
    val appName: String = "UpRight",

    // Permission
    val realtimeMonitor: String,
    val cameraNeeded: String,
    val grantCamera: String,

    // Calibration
    val calibSuccess: String,
    val calibFailed: String,
    val calibCleared: String,
    val calibTitle: String,
    val calibDesc: String,
    val calibStep1: String,
    val calibStep2: String,
    val calibStep3: String,
    val startCalibration: String,
    val calibrating: String,
    val calibrated: String,
    val notCalibrated: String,
    val clearCalibration: String,
    val recalibrate: String,
    val calibManagement: String,
    val calibStatus: String,
    val clearCalibConfirm: String,

    // Posture states
    val goodPosture: String,
    val headTilt: String,
    val shoulderUneven: String,
    val forwardHead: String,
    val hunchback: String,
    val noPerson: String,
    val sitInFront: String,

    // Status badges
    val statusGood: String,
    val statusNone: String,
    val statusBad: String,

    // Overlays
    val ecoMode: String,
    val ecoModeDesc: String,
    val paused: String,
    val autoResumeIn: (Int, Int) -> String,
    val noPersonPause: String,
    val pauseAction: String,
    val ignoreAction: String,

    // Controls
    val preview: String,
    val pause: String,
    val resume: String,
    val calibrate: String,
    val hide: String,
    val debug: String,

    // Settings
    val settings: String,
    val alertInterval: String,
    val alertIntervalDesc: String,
    val soundSection: String,
    val soundLabel: String,
    val soundDesc: String,
    val vibration: String,
    val vibrationDesc: String,
    val sensitivity: String,
    val sensLow: String,
    val sensMedium: String,
    val sensHigh: String,
    val sensLowDesc: String,
    val sensMediumDesc: String,
    val sensHighDesc: String,
    val language: String,
    val autoResume: String,
    val ecoModeSection: String,
    val ecoModeDesc2: String,
    val about: String,
    val version: String,
    val aboutDesc: String,
    val cancel: String,
    val back: String,

    // Onboarding
    val onbTitle1: String,
    val onbDesc1: String,
    val onbTitle2: String,
    val onbSubtitle2: String,
    val onbDesc2: String,
    val onbTitle3: String,
    val onbSubtitle3: String,
    val onbDesc3: String,
    val next: String,
    val getStarted: String,
    val skipCalib: String,

    // History
    val loading: String,
    val history: String,
    val todayGoal: String,
    val goalDesc: String,
    val streak: String,
    val streakUnit: String,
    val weeklyTrend: String,
    val todayRecords: String,
    val noRecords: String,
    val noRecordsHint: String,
    val goalMet: String,
    val dayNames: List<String>,

    // Notifications
    val notifRunning: String,
    val notifChannel: String,
    val notifChannelDesc: String,
    val notifStop: String,
    val notifUnknown: String,

    // Time units
    val seconds: List<String>,
    val minutes: List<String>,

    // Back press
    val pressBackAgain: String,

    // Positioning guide
    val positionTitle: String,
    val positionHint: String,
    val positionGood: String,
)

val StringsZh = S(
    realtimeMonitor = "实时坐姿监测",
    cameraNeeded = "需要相机权限来分析您的坐姿",
    grantCamera = "授权相机",
    calibSuccess = "校准成功",
    calibFailed = "校准失败，请确保坐在摄像头前方",
    calibCleared = "校准已清除",
    calibTitle = "坐姿校准",
    calibDesc = "校准会记录你当前的坐姿作为「标准姿势」，后续检测会以此为基准判断偏差。",
    calibStep1 = "先调整到正确坐姿",
    calibStep2 = "保持 3 秒完成采集",
    calibStep3 = "校准结果自动保存，下次无需重新校准",
    startCalibration = "开始校准",
    calibrating = "校准中...",
    calibrated = "已校准",
    notCalibrated = "未校准",
    clearCalibration = "清除校准",
    recalibrate = "重新校准",
    calibManagement = "校准管理",
    calibStatus = "校准状态",
    clearCalibConfirm = "确定要清除校准数据吗？清除后将使用默认阈值进行检测。",
    goodPosture = "坐姿良好",
    headTilt = "头部侧歪",
    shoulderUneven = "肩膀不平",
    forwardHead = "头部前倾",
    hunchback = "驼背",
    noPerson = "未检测到人",
    sitInFront = "请坐在摄像头前方",
    statusGood = "良好",
    statusNone = "无人",
    statusBad = "异常",
    ecoMode = "省电模式",
    ecoModeDesc = "检测仍在后台运行",
    paused = "已暂停",
    autoResumeIn = { min, sec -> "${min}分${sec}秒后自动恢复" },
    noPersonPause = "长时间未检测到人，是否暂停监测？",
    pauseAction = "暂停",
    ignoreAction = "忽略",
    preview = "画面",
    pause = "暂停",
    resume = "继续",
    calibrate = "校准",
    hide = "隐藏",
    debug = "调试",
    settings = "设置",
    alertInterval = "提醒间隔",
    alertIntervalDesc = "不良姿势持续 1 分钟后按此间隔播放提示音",
    soundSection = "提示音",
    soundLabel = "声音提醒",
    soundDesc = "坐姿异常时播放乌鸦叫声提醒",
    vibration = "震动反馈",
    vibrationDesc = "姿态异常时震动提醒",
    sensitivity = "检测灵敏度",
    sensLow = "低",
    sensMedium = "中",
    sensHigh = "高",
    sensLowDesc = "较低的灵敏度，减少误报",
    sensMediumDesc = "默认灵敏度，平衡准确性和体验",
    sensHighDesc = "较高的灵敏度，更及时提醒",
    language = "界面语言",
    autoResume = "暂停后自动恢复",
    ecoModeSection = "省电模式",
    ecoModeDesc2 = "关闭预览画面，降低检测频率",
    about = "关于",
    version = "版本",
    aboutDesc = "UpRight 使用设备端 AI 进行实时坐姿监测，无需网络连接。",
    cancel = "取消",
    back = "返回",
    onbTitle1 = "实时坐姿监测助手",
    onbDesc1 = "利用手机前置摄像头和 AI 技术，\n实时监测您的坐姿状态，\n帮助您养成健康的工作习惯。",
    onbTitle2 = "手机摆放建议",
    onbSubtitle2 = "获得最佳检测效果",
    onbDesc2 = "• 将手机放在正前方，与视线等高\n• 前置摄像头朝向自己\n• 保持 0.5-1.5 米的距离\n• 确保光线充足",
    onbTitle3 = "个性化校准",
    onbSubtitle3 = "记录您的标准坐姿",
    onbDesc3 = "校准会记录您正确坐姿的姿态数据，\n后续检测会以此为基准。\n建议在坐姿端正时进行校准。",
    next = "下一步",
    getStarted = "开始使用",
    skipCalib = "跳过，稍后再校准",
    loading = "加载中...",
    history = "历史记录",
    todayGoal = "今日目标",
    goalDesc = "80% 良好坐姿",
    streak = "连续达标",
    streakUnit = "天",
    weeklyTrend = "近 7 天坐姿趋势",
    todayRecords = "今日记录",
    noRecords = "今天还没有监测记录",
    noRecordsHint = "开始监测后会自动保存数据",
    goalMet = "已达标",
    dayNames = listOf("一", "二", "三", "四", "五", "六", "日"),
    notifRunning = "坐姿监测运行中",
    notifChannel = "坐姿监测",
    notifChannelDesc = "后台坐姿监测服务",
    notifStop = "停止",
    notifUnknown = "未知",
    seconds = listOf("5秒", "10秒", "30秒", "60秒"),
    minutes = listOf("5分钟", "10分钟", "15分钟", "20分钟"),
    pressBackAgain = "再按一次退出",
    positionTitle = "调整位置",
    positionHint = "请将上半身放入框内",
    positionGood = "位置合适！",
)

val StringsEn = S(
    realtimeMonitor = "Real-time Posture Monitor",
    cameraNeeded = "Camera permission needed for posture analysis",
    grantCamera = "Grant Camera",
    calibSuccess = "Calibration successful",
    calibFailed = "Calibration failed. Make sure you're in front of the camera",
    calibCleared = "Calibration cleared",
    calibTitle = "Posture Calibration",
    calibDesc = "Calibration records your current posture as a baseline for future comparisons.",
    calibStep1 = "Adjust to correct posture first",
    calibStep2 = "Hold for 3 seconds",
    calibStep3 = "Results saved automatically, no need to recalibrate",
    startCalibration = "Start Calibration",
    calibrating = "Calibrating...",
    calibrated = "Calibrated",
    notCalibrated = "Not Calibrated",
    clearCalibration = "Clear",
    recalibrate = "Recalibrate",
    calibManagement = "Calibration",
    calibStatus = "Calibration Status",
    clearCalibConfirm = "Clear calibration data? Default thresholds will be used.",
    goodPosture = "Good Posture",
    headTilt = "Head Tilting",
    shoulderUneven = "Uneven Shoulders",
    forwardHead = "Forward Head",
    hunchback = "Slouching",
    noPerson = "No Person Detected",
    sitInFront = "Please sit in front of the camera",
    statusGood = "Good",
    statusNone = "None",
    statusBad = "Bad",
    ecoMode = "Eco Mode",
    ecoModeDesc = "Detection running in background",
    paused = "Paused",
    autoResumeIn = { min, sec -> "Resumes in ${min}m ${sec}s" },
    noPersonPause = "No person detected for a while. Pause monitoring?",
    pauseAction = "Pause",
    ignoreAction = "Ignore",
    preview = "Preview",
    pause = "Pause",
    resume = "Resume",
    calibrate = "Calibrate",
    hide = "Hide",
    debug = "Debug",
    settings = "Settings",
    alertInterval = "Alert Interval",
    alertIntervalDesc = "Plays at this interval after bad posture persists for 1 min",
    soundSection = "Sound",
    soundLabel = "Sound Alerts",
    soundDesc = "Plays crow caw when bad posture persists",
    vibration = "Vibration",
    vibrationDesc = "Vibrate when bad posture detected",
    sensitivity = "Sensitivity",
    sensLow = "Low",
    sensMedium = "Medium",
    sensHigh = "High",
    sensLowDesc = "Lower sensitivity, fewer false alerts",
    sensMediumDesc = "Default sensitivity, balanced",
    sensHighDesc = "Higher sensitivity, more responsive",
    language = "Language",
    autoResume = "Auto Resume After Pause",
    ecoModeSection = "Eco Mode",
    ecoModeDesc2 = "Turn off preview, reduce detection frequency",
    about = "About",
    version = "Version",
    aboutDesc = "UpRight uses on-device AI for real-time posture monitoring. No internet required.",
    cancel = "Cancel",
    back = "Back",
    onbTitle1 = "Real-time Posture Monitor",
    onbDesc1 = "Uses front camera and AI\nto monitor your posture in real time\nand build healthy work habits.",
    onbTitle2 = "Phone Placement Tips",
    onbSubtitle2 = "For best detection results",
    onbDesc2 = "• Place phone at eye level in front of you\n• Front camera facing you\n• Keep 0.5-1.5m distance\n• Ensure good lighting",
    onbTitle3 = "Personalized Calibration",
    onbSubtitle3 = "Record your standard posture",
    onbDesc3 = "Calibration records your correct posture\nas a baseline for future comparisons.\nCalibrate while sitting with good posture.",
    next = "Next",
    getStarted = "Get Started",
    skipCalib = "Skip, calibrate later",
    loading = "Loading...",
    history = "History",
    todayGoal = "Today's Goal",
    goalDesc = "80% good posture",
    streak = "Streak",
    streakUnit = "days",
    weeklyTrend = "7-Day Posture Trend",
    todayRecords = "Today's Records",
    noRecords = "No records today",
    noRecordsHint = "Data saves automatically when monitoring",
    goalMet = "Goal Met",
    dayNames = listOf("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"),
    notifRunning = "Posture monitoring active",
    notifChannel = "Posture Monitor",
    notifChannelDesc = "Background posture monitoring service",
    notifStop = "Stop",
    notifUnknown = "Unknown",
    seconds = listOf("5s", "10s", "30s", "60s"),
    minutes = listOf("5m", "10m", "15m", "20m"),
    pressBackAgain = "Press back again to exit",
    positionTitle = "Adjust Position",
    positionHint = "Place your upper body in the frame",
    positionGood = "Perfect!",
)

fun stringsFor(lang: AlertLanguage) = when (lang) {
    AlertLanguage.ZH -> StringsZh
    AlertLanguage.EN -> StringsEn
}
